apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: production          
  labels:
    app.kubernetes.io/name: fastapi-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  revisionHistoryLimit: 3        
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-app
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: api
    spec:
      automountServiceAccountToken: false  
      terminationGracePeriodSeconds: 30     
      securityContext:
        runAsNonRoot: true                 
        runAsUser: 1000                    
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault            
      containers:
        - name: fastapi-app
          image: ghcr.io/roma-rgb-tech/devsecops-pipeline-demo:1.0.0
          imagePullPolicy: Always           
          ports:
            - name: http                   
              containerPort: 8000
              protocol: TCP
          env:
            - name: APP_ENV
              value: "production"
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false  
            readOnlyRootFilesystem: true    
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL                   


          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12           
            successThreshold: 1


          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0       
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5


          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
